-- ============================================================
-- Projet 3 — Hub'Eau · Infrastructure Snowflake
-- Créé le 10/09/2026
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Rôle du projet
CREATE ROLE IF NOT EXISTS TRANSFORMHUBEAU;

-- Database
CREATE DATABASE IF NOT EXISTS DATABASE_HUBEAU;

-- Schemas
CREATE SCHEMA IF NOT EXISTS DATABASE_HUBEAU.STAGING;
CREATE SCHEMA IF NOT EXISTS DATABASE_HUBEAU.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DATABASE_HUBEAU.MARTS;
CREATE SCHEMA IF NOT EXISTS DATABASE_HUBEAU.CI;
CREATE SCHEMA IF NOT EXISTS DATABASE_HUBEAU.CI_STAGING;
CREATE SCHEMA IF NOT EXISTS DATABASE_HUBEAU.CI_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DATABASE_HUBEAU.CI_MARTS;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS WH_HUBEAU
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Resource monitor (portée warehouse, pas compte)
CREATE RESOURCE MONITOR IF NOT EXISTS RM_HUBEAU WITH
  CREDIT_QUOTA = 10
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  NOTIFY_USERS = ('ONIZUKA01')
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE IF EXISTS WH_HUBEAU SET RESOURCE_MONITOR = RM_HUBEAU;

-- Grants : database et warehouse
GRANT USAGE ON DATABASE DATABASE_HUBEAU TO ROLE TRANSFORMHUBEAU;
GRANT USAGE ON WAREHOUSE WH_HUBEAU TO ROLE TRANSFORMHUBEAU;

-- Grants : schemas
GRANT USAGE ON SCHEMA DATABASE_HUBEAU.STAGING TO ROLE TRANSFORMHUBEAU;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA DATABASE_HUBEAU.STAGING TO ROLE TRANSFORMHUBEAU;

GRANT USAGE ON SCHEMA DATABASE_HUBEAU.INTERMEDIATE TO ROLE TRANSFORMHUBEAU;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DATABASE_HUBEAU.INTERMEDIATE TO ROLE TRANSFORMHUBEAU;

GRANT USAGE ON SCHEMA DATABASE_HUBEAU.MARTS TO ROLE TRANSFORMHUBEAU;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DATABASE_HUBEAU.MARTS TO ROLE TRANSFORMHUBEAU;

GRANT USAGE ON SCHEMA DATABASE_HUBEAU.CI TO ROLE TRANSFORMHUBEAU;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DATABASE_HUBEAU.CI TO ROLE TRANSFORMHUBEAU;

GRANT USAGE ON SCHEMA DATABASE_HUBEAU.CI_STAGING TO ROLE TRANSFORMHUBEAU;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA DATABASE_HUBEAU.CI_STAGING TO ROLE TRANSFORMHUBEAU;

GRANT USAGE ON SCHEMA DATABASE_HUBEAU.CI_INTERMEDIATE TO ROLE TRANSFORMHUBEAU;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DATABASE_HUBEAU.CI_INTERMEDIATE TO ROLE TRANSFORMHUBEAU;

GRANT USAGE ON SCHEMA DATABASE_HUBEAU.CI_MARTS TO ROLE TRANSFORMHUBEAU;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DATABASE_HUBEAU.CI_MARTS TO ROLE TRANSFORMHUBEAU;

-- Attribution du rôle
GRANT ROLE TRANSFORMHUBEAU TO USER ONIZUKA01;

-- ============================================================
-- Objets créés sous le rôle du projet
-- ============================================================

USE ROLE TRANSFORMHUBEAU;
USE SCHEMA DATABASE_HUBEAU.STAGING;

CREATE OR ALTER STAGE hubeau_stage
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE OR ALTER FILE FORMAT ff_csv
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
--  ENCODING = 'ISO88591'
  ;

-- TODO : CREATE TABLE — après décision du grain (Phase 1, séance 1.5)